# Generated by Django 3.1.7 on 2021-03-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210305_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='mark',
            field=models.FloatField(null=True, verbose_name='Оценка'),
        ),
    ]
