# Generated by Django 3.1.7 on 2021-03-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='for_payment',
            field=models.CharField(default='get_total_cost()', max_length=50),
        ),
    ]
