# Generated by Django 3.1.7 on 2021-03-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_for_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.CharField(choices=[('Кафе "Анютина лавка" Главный офис Россия, Москва, улица Арбат,1', 'Россия, Москва, улица Арбат,1'), ('Кафе "Анютина лавка" Шараповский пр., вл, Мытищи Торговый Центр "Красный Кит"', 'Шараповский пр., вл, Мытищи Торговый Центр "Красный Кит"'), ('Кафе "Анютина лавка" 1, район Новокуркино, 8-й микрорайон, Химки ТРЦ МЕГА', '1, район Новокуркино, 8-й микрорайон, Химки ТРЦ МЕГА')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='for_payment',
            field=models.CharField(max_length=50),
        ),
    ]
